/* Generated by bin2c, do not edit manually */

/* Contents of file segcount_call.bin */
const long int segcount_call_bin_size = 13;
const unsigned char segcount_call_bin[13] = {
    0x07, 0x03, 0x00, 0x54, 0x3F, 0x00, 0x0A, 0x31, 0x00, 0x03, 0x06, 0x04, 0x40
};
