/* Generated by bin2c, do not edit manually */

/* Contents of file segcount.bin */
const long int segcount_bin_size = 9;
const unsigned char segcount_bin[9] = {
    0x07, 0x03, 0x00, 0x54, 0x06, 0x04, 0x31, 0x00, 0x03
};
